# Generated by Django 3.0.7 on 2020-07-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duka', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity_available',
            field=models.IntegerField(default=1),
        ),
    ]
