# Generated by Django 3.0.7 on 2020-07-31 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duka', '0005_auto_20200731_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(default='@gmail', max_length=50),
        ),
    ]
