# Generated by Django 3.0.7 on 2020-07-31 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duka', '0011_auto_20200731_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
    ]
