# Generated by Django 3.0.7 on 2020-07-31 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duka', '0012_remove_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='gnao', max_length=50),
        ),
    ]
