# Generated by Django 3.0.7 on 2020-07-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duka', '0013_order_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(default='gnao', max_length=50),
        ),
    ]
