# Generated by Django 3.0.7 on 2020-07-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duka', '0014_auto_20200731_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
