# Generated by Django 3.0.7 on 2020-07-31 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('duka', '0015_auto_20200731_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
