# Generated by Django 3.0.7 on 2020-08-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duka', '0016_auto_20200731_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
