# Generated by Django 3.0.7 on 2020-08-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200803_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_payable',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
