# Generated by Django 3.0.7 on 2020-08-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_total_payable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
